version: "3.7"
services:
  ngnix:
    image: nginx:1.19.5
    volumes:
      - /home/nginx_setting/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
    networks:
      - network
    ports:
      - 80:80

  django_container_gunicorn:
    image: django_test_image:1
    networks:
      - network
    volumes:
      - static-volume:/home/dev/BACKEND/staticfiles
    secrets:
      - MYSQL_PASSWORD
      - DJANGO_SECRET_KEY

  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - maria-database:/var/lib/mysql
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      MYSQL_DATABASE: poppymail_db
      MYSQL_USER: root
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD

networks:
  network:

volumes:
  maria-database:
  static-volume:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MYSQL_PASSWORD:
    external: true
  MYSQL_ROOT_PASSWORD:
    external: true